
package org.ipn.escom.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HolaMundoService", targetNamespace = "http://soap.escom.ipn.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HolaMundoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saludar", targetNamespace = "http://soap.escom.ipn.org/", className = "org.ipn.escom.soap.Saludar")
    @ResponseWrapper(localName = "saludarResponse", targetNamespace = "http://soap.escom.ipn.org/", className = "org.ipn.escom.soap.SaludarResponse")
    @Action(input = "http://soap.escom.ipn.org/HolaMundoService/saludarRequest", output = "http://soap.escom.ipn.org/HolaMundoService/saludarResponse")
    public String saludar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
