
package org.ipn.escom.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HolaMundoServiceImplService", targetNamespace = "http://soap.escom.ipn.org/", wsdlLocation = "http://desktop-89os5a4:8080/HolaMundoServiceImplService/HolaMundoServiceImpl?wsdl")
public class HolaMundoServiceImplService
    extends Service
{

    private final static URL HOLAMUNDOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOLAMUNDOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HOLAMUNDOSERVICEIMPLSERVICE_QNAME = new QName("http://soap.escom.ipn.org/", "HolaMundoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://desktop-89os5a4:8080/HolaMundoServiceImplService/HolaMundoServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOLAMUNDOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HOLAMUNDOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HolaMundoServiceImplService() {
        super(__getWsdlLocation(), HOLAMUNDOSERVICEIMPLSERVICE_QNAME);
    }

    public HolaMundoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOLAMUNDOSERVICEIMPLSERVICE_QNAME, features);
    }

    public HolaMundoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HOLAMUNDOSERVICEIMPLSERVICE_QNAME);
    }

    public HolaMundoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOLAMUNDOSERVICEIMPLSERVICE_QNAME, features);
    }

    public HolaMundoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HolaMundoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HolaMundoService
     */
    @WebEndpoint(name = "HolaMundoServiceImplPort")
    public HolaMundoService getHolaMundoServiceImplPort() {
        return super.getPort(new QName("http://soap.escom.ipn.org/", "HolaMundoServiceImplPort"), HolaMundoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolaMundoService
     */
    @WebEndpoint(name = "HolaMundoServiceImplPort")
    public HolaMundoService getHolaMundoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.escom.ipn.org/", "HolaMundoServiceImplPort"), HolaMundoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOLAMUNDOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HOLAMUNDOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HOLAMUNDOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
